
CREATE TABLE IF NOT EXISTS b3_acoes (
    tipreg  text,
    dtpreg  date,
    codbdi  text,
    codneg  text,
    tpmerc  text,
    nomres  text,
    especi  text,
    prazot  text,
    modref  text,
    preabe  double precision,
    premax  double precision,
    premin  double precision,
    premed  double precision,
    preult  double precision,
    preofc  double precision,
    preofv  double precision,
    totneg  bigint,
    quatot  bigint,
    voltot  double precision,
    preexe  double precision,
    indopc  text,
    datven  date,
    fatcot  text,
    ptoexe  double precision,
    codisi  text,
    dismes  text
);
